# Usa una imagen oficial de Python ligera
FROM python:3.12-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo de requerimientos e instálalos
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código
COPY ./app ./app

# Expone el puerto en el que correrá FastAPI
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["uvicorn", "app.main:app","--host", "0.0.0.0","--port", "5000", "--reload"]